### ISSUE TITLE
Obtaining the token

### ISSUE THREAD

**Issue by d-motzer** [REVENGE977/Discord-Bots-Hack#21]
Hello. I am trying to get into a private discord.
A bot is in that server and it sends invites out in an email after you paid to get in.
I have an old invite, but i am now removed from this server.

Where can i get a token to use this hack?

**Comment by danmitzer** [comment]
the service it uses to send invites and the bots name is Launchpass

**Comment by dynamicdiscord** [comment]
You cannot obtain the token of someone else's bot. Feel free to attempt it but it is not possible. Try making your own bot and running it.

**Comment by Quatrecentquatre-404** [comment]
This is not an issue related to the code itself, please, close it.
Thanks.

**Comment by AstroOrbis** [comment]
I believe there is a way. Isn't the start of all tokens the ID in base64? Then the password, also in Base64? You could attempt to get the most used passwords from SecLists, then encrypt them all, and make a simple python script to merge all of them, then test them one by one, deleting the tokens that are invalid. Just an idea :)

**Comment by dynamicdiscord** [comment]
doesn't work like that. bot tokens are completely separate from user
accounts / passwords and the tokens are randomly generated 59-60 character
phrases.
The bot tokens are similar to User Tokens, except they act more as private
keys.

**Comment by Quatrecentquatre-404** [comment]
No I think AstroOrbis is right about the account informations in the token. At least, for a user account. It might be a hash generated  from the email, password, timestamp of the account creation and finally the ID of the account :
ID.HASH(TIMESTAMP.INFO_DATA)
That's what I'm thinking. But for a bot, it couldn't be the same thing because they don't have emails or this kind of thing. Excepted if it's based on the owner's one. And then, when you click regen for th etoken, it takes the new timestamp to change the hash. Or if it's a Bcrypt/Argon's one, no need to update timestamp, there is many hash for the same string.

The point is, you can't guess this part of the token. Basicly, yes, the token starts by the account's ID encoded in Base64, but about the nex tpart of the string, we don't really know.

**Comment by dynamicdiscord** [comment]
I can log straight into bot accounts and act as if it's a user account, and
they have no bound email and password. You can't claim the account either,
as with a noneregistered account.

**Comment by Quatrecentquatre-404** [comment]
Yeah, I didn't meant bot's account owns emails and passwords. What I meant is that a part of their token **might** be calculated from the owner's account.

**Comment by AstroOrbis** [comment]
Random question: Would it be possible to get every single token possible (About 16 billion last time I checked, not sure what that file size would be, but if its 5 TB or under it's fine for me), make a botnet script to attempt to find all the valid ones and save them to another file (keep the original for new accounts), then try to log in, grab the user ID of the account, and if it's the same as the one you're looking for it just `print`s it back?

**Comment by dynamicdiscord** [comment]
Probably, although it would take a painstakingly long amount of time (up to
years) unless you had thousands of computers working on it, by then,
though, it might be classified as a ddos attack.

**Comment by AstroOrbis** [comment]
Distributed computing maybe?

**Comment by dynamicdiscord** [comment]
I've seen some incredible things with Folding@Home, although this probably
wouldn't be a priority for them as it's kind of invasion of privacy //
similar. They managed to find a single string out of 2^64 possibilities

**Comment by AstroOrbis** [comment]
Imagine this. A botnet with over 3 million people on it. All from high-end PCs to iPhones. Would it be possible? Theoretically?

**Comment by dynamicdiscord** [comment]
Yeah! It would be similar to the bitcoin mining scenario. Depending on how
much process power the devices have, we could theoretically crack every
single one in half a year.

Keep in mind, people can refresh / change their tokens as well.

**Comment by AstroOrbis** [comment]
But then we would already have it. We could split the workload into groups... for example, all tokens starting with A in one group, B with another... then sub groups... yeah this is getting out of hand kek

**Comment by Quatrecentquatre-404** [comment]
> Random question: Would it be possible to get every single token possible (About 16 billion last time I checked, not sure what that file size would be, but if its 5 TB or under it's fine for me), make a botnet script to attempt to find all the valid ones and save them to another file (keep the original for new accounts), then try to log in, grab the user ID of the account, and if it's the same as the one you're looking for it just `print`s it back?

According to my maths, it should be a file of 11.3Mo max. I say max because some tokens are 24+6+27 chars (not MFA's one) and 3+1+84 chars (MFA's one). I assumed all tokens would be MFA.
```python
mfa_token_size = len(f"mfa.{'A'*84}")*8 # MFA Token size encoded in bytes
size_o = mfa_token_size*16_000_000
size_mo = size_o*(10**-6)
print(size_mo)
11264
```

**Comment by AstroOrbis** [comment]
so the entire file would be 11 megabytes?

**Comment by AstroOrbis** [comment]
for every single possible token?

**Comment by Quatrecentquatre-404** [comment]
> for every single possible token?

Theorically, yes. If all tokens are MFA. Because they are wider than other. They are 84 + 1 + 3 chars. So, it would be a less because not everyone enabled 2FA.

**Comment by AstroOrbis** [comment]
How long would it take to compile a list?

**Comment by AstroOrbis** [comment]
Making a program that runs through them to check valid ones, we can just use a python script that grabs each line, and checks the discord login API to see if its valid

**Comment by AstroOrbis** [comment]
> I've seen some incredible things with Folding@Home, although this probably wouldn't be a priority for them as it's kind of invasion of privacy // similar. They managed to find a single string out of 2^64 possibilities
> […](#)

We don’t need to find 1 string, we need every string possible.

**Comment by AstroOrbis** [comment]
Also, as an example, I created a bot called TesterBot with an application ID of `836652271461990420` and an oAuth client ID of `836652271461990420` as well. The token is `ODM2NjUyMjcxNDYxOTkwNDIw.YIhHJQ.IecZCtVlox25uqBomIOcB4YR6U0`, and when put through Base64 de-encoding, it gives `836652271461990420`G%qVZ1ۛ9xa`. This looks like the bot tokens are the ID + a seemingly random string of characters. Note the 3 dots on top of the 9 in the de-encoded string.

**Comment by dynamicdiscord** [comment]
Here's something interesting.
https://user-images.githubusercontent.com/6506416/81051916-dd8c9900-8ec2-11ea-8794-daf12d6f31f0.png

**Comment by AstroOrbis** [comment]
So we just have to guess the HMAC part?

**Comment by Quatrecentquatre-404** [comment]
Thanks for sharing the link. I was sure I'm right about ID and timestamp.

**Comment by Quatrecentquatre-404** [comment]
> Making a program that runs through them to check valid ones, we can just use a python script that grabs each line, and checks the discord login API to see if its valid

It depends of the computer's power and the proxies you would use to check, because of retry_after in JSON response that you have to handle.

**Comment by AstroOrbis** [comment]
Isn't there the rule of 5/5/5? More than 5 requests in 5 seconds gives you a 5 minute timeout?

**Comment by Quatrecentquatre-404** [comment]
> Isn't there the rule of 5/5/5? More than 5 requests in 5 seconds gives you a 5 minute timeout?

I don't think Discord implements this. It just returns the timeout in ms you have to wait for the next request if it's specified. Else, you can continue to POST.
