### ISSUE TITLE
CAN I GET SOME HELP PLS

### ISSUE THREAD

**Issue by SniperXKiller** [REVENGE977/Discord-Bots-Hack#22]
Hi, SXK here
I don't do JS, so I need help on Step 3 and up.
The Bot I am trying to hack is Myuu Bot.
PLEASE HELP ME!!!

**Comment by KAMUI966** [comment]
read the readme file, you need the bot token .

**Comment by RC24Gaming** [comment]
help me about this
Cannot read property 'get' of undefined
