### ISSUE TITLE
I looked through the code and I just want to say it: it works! No token grabber, no shenanigans :)

### ISSUE THREAD

**Issue by AstroOrbis** [REVENGE977/Discord-Bots-Hack#30]

**Comment by gabrielcodeak** [comment]
Lmao lot of cap

**Comment by AstroOrbis** [comment]
lmao this sounds reallly sus but i swear on my beanigun

**Comment by endlessXD** [comment]
> Lmao lot of cap

no its not a token grabber I just checked

**Comment by Quatrecentquatre-404** [comment]
Thanks to support our work, but this category is reserved for issues, not commentaries.

**Comment by AstroOrbis** [comment]
:)
